Repository FragLand/minestat, pull requests merged in 2021-02, with the labels that each got.

#55 Move documents and add Python package
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/README.md
  .github/pull_request_template.md
  .gitignore
  LICENSE.txt
  Python/LICENSE.txt
  Python/README.md
  Python/minestat/__init__.py
  Python/pyproject.toml
  Python/setup.cfg
  docs/CODE_OF_CONDUCT.md
  docs/ISSUE_TEMPLATE.md
  docs/PULL_REQUEST_TEMPLATE.md
Labels: documentation, new feature

#60 Add Perl CPAN module
  .github/README.md
  .gitignore
  Perl/MineStat.pm
  Perl/Minecraft-ServerStatus/Changes
  Perl/Minecraft-ServerStatus/LICENSE
  Perl/Minecraft-ServerStatus/MANIFEST
  Perl/Minecraft-ServerStatus/Makefile.PL
  Perl/Minecraft-ServerStatus/README.md
  Perl/Minecraft-ServerStatus/lib/Minecraft/ServerStatus.pm
  Perl/example.pl
Labels: new feature

#61 Add NuGet package and DLL
  .github/README.md
  .gitignore
  CSharp/Example.cs
  CSharp/MineStat.cs
  CSharp/MineStat.sln
  CSharp/MineStat/MineStat.cs
  CSharp/MineStat/MineStat.csproj
  CSharp/MineStat/MineStat.nuspec
  CSharp/MineStat/Properties/AssemblyInfo.cs
Labels: new feature

#63 Add PHP package and update badge links
  .github/README.md
  PHP/composer.json
  PHP/minestat.php
Labels: documentation, new feature

#65 New Python module, supporting all ping types
  .gitignore
  Python/example.py
  Python/minestat/__init__.py
  Python/setup.cfg
Labels: documentation, enhancement, new feature

#67 Add @MindSolve as Python author [skip ci]
  Python/minestat/__init__.py
Labels: documentation
