Repository FragLand/minestat, pull requests merged in 2021-03, with the labels that each got.

#68 Feature: [Python]: Replace slp_protocol strings with proper Enum
  Python/minestat/__init__.py
  Python/setup.cfg
Labels: enhancement, new feature

#69 Bugfix: [Python]: Old version compatibility
  Python/minestat/__init__.py
  Python/setup.cfg
Labels: bug

#71 Reorder SLP requests and add request type
  .github/README.md
  Java/Example.java
  Java/me/dilley/MineStat.java
  PHP/composer.json
  PHP/example.php
  PHP/minestat.php
  Python/README.md
  Python/minestat/__init__.py
  Ruby/example.rb
  Ruby/lib/minestat.rb
  Ruby/minestat.gemspec
Labels: bug, documentation, enhancement, hygiene, new feature

#72 Add AppVeyor, fix Travis CI, increment Perl package version
  .github/README.md
  .travis.yml
  Perl/Minecraft-ServerStatus/Changes
  Perl/Minecraft-ServerStatus/README.md
  Perl/Minecraft-ServerStatus/lib/Minecraft/ServerStatus.pm
  appveyor.yml
Labels: documentation, new feature

#73 Add Ant, Gradle, and Maven build support for Java
  .gitignore
  Java/Test/me/dilley/MineStatTest.java
  Java/build.gradle
  Java/build.xml
  Java/gradle.properties
  Java/pom.xml
Labels: new feature

#74 Add SLP 1.7 support for Java
  .travis.yml
  Java/build.gradle
  Java/me/dilley/MineStat.java
  Java/pom.xml
Labels: new feature
