Repository FragLand/minestat, pull requests merged in 2021-09, with the labels that each got.

#89 [Java] Feature: MOTD format stripping / bungeecord fixes
  .github/README.md
  Java/Example.java
  Java/me/dilley/MineStat.java
Labels: bug, enhancement, new feature

#92 PHP: Stripped MotD support
  .github/README.md
  PHP/composer.json
  PHP/example.php
  PHP/minestat.php
Labels: bug, enhancement, new feature

#93 Fix PHP motd array/string issues
  PHP/composer.json
  PHP/minestat.php
Labels: bug

#95 Updated Ruby version's documentation
  Ruby/lib/minestat.rb
Labels: documentation

#96 Fix Ruby motd array/string issues
  Ruby/lib/minestat.rb
  Ruby/minestat.gemspec
Labels: bug
