Repository FragLand/minestat, pull requests merged in 2022-08, with the labels that each got.

#110 Replace Travis CI with Github Actions and add actions for packaging and publishing
  .github/README.md
  .github/workflows/CodeQL.yml
  .github/workflows/Maven-publish.yml
  .github/workflows/Powershell-publish.yml
  .github/workflows/PyPI-publish.yml
  .github/workflows/npm-publish.yml
  .github/workflows/nuget-publish.yml
  .github/workflows/rubygem-publish.yml
  .travis.yml
  Go/minestat/go.mod
  Java/pom.xml
Labels: enhancement, wishlist, lang: ALL, package management

#114 Nuget publish github action bugfix
  .github/workflows/Powershell-publish.yml
  .github/workflows/nuget-publish.yml
  CSharp/MineStat/MineStat.csproj
  CSharp/MineStat/MineStat.nuspec
  CSharp/MineStat/Properties/AssemblyInfo.cs
  PowerShell/MineStat/MineStat.psd1
  PowerShell/MineStat/MineStat.psm1
  appveyor.yml
Labels: bug, lang: C#, package management

#116 Java Bedrock support
  Java/Example.java
  Java/me/dilley/MineStat.java
  Java/pom.xml
Labels: enhancement, new feature, lang: Java
